# Generated by Django 5.1.3 on 2024-11-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_artoniauser_groups_and_more'),
        ('macrame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='macrames', to='accounts.artoniauser'),
        ),
    ]
