# Generated by Django 5.1.3 on 2024-11-24 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrame', '0002_macrame_difficulty_level_macrame_knot_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='macrame',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_macrames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='macrame',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
