# Generated by Django 5.1.3 on 2024-11-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPainting',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.product')),
            ],
            bases=('common.product',),
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('Oil Painting', 'Oil Painting'), ('Acrilic Painting', 'Acrilic Painting'), ('Watercolor Painting', 'Watercolor Painting'), ('Gouache Painting', 'Gouache Painting'), ('Spray Painting', 'Spray Painting'), ('Mixed Media', 'Mixed Media'), ('Other', 'Other')], default='Other', max_length=20)),
                ('image_url', models.URLField()),
                ('art_painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_painting', to='art_painting.artpainting')),
            ],
        ),
    ]
