# Generated by Django 5.1.3 on 2024-11-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_artoniauser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='art_painting', to='accounts.artoniauser')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('Oil Painting', 'Oil Painting'), ('Acrilic Painting', 'Acrilic Painting'), ('Watercolor Painting', 'Watercolor Painting'), ('Gouache Painting', 'Gouache Painting'), ('Spray Painting', 'Spray Painting'), ('Mixed Media', 'Mixed Media'), ('Other', 'Other')], default='Other', max_length=20)),
                ('image_url', models.URLField()),
                ('art_painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_painting', to='art_painting.artpainting')),
            ],
        ),
    ]
